spring:
  application:
    name: recargapay-wallet
  
  datasource:
    url: jdbc:postgresql://localhost:5432/recargapay_wallet
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 20000
      idle-timeout: 300000
      leak-detection-threshold: 60000
      validation-timeout: 5000

  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true

  transaction:
    default-timeout: 30s

  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
    db:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Recarga Pay Digital Wallet API
    description: API para sistema de carteira digital
    version: 1.0.0
    contact:
      name: Jeferson
      email: jefersonmartinsbsantos@gmail.com




livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10


logging:
  level:
    br.com.jefersonmbs.recargapaywallet: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE